import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${geistMono.variable} ${nunito.variable} h-full antialiased`}
    >
      <body>
        {children}
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 4000,
            style: {
              background: "#0a0a0a",
              color: "#fff",
              border: "1px solid rgba(255,255,255,0.15)",
              fontFamily: "monospace",
              fontSize: "12px",
              letterSpacing: "0.05em",
              padding: "12px 16px",
              borderRadius: "8px",
            },
            success: {
              iconTheme: {
                primary: "#fff",
                secondary: "#0a0a0a",
              },
            },
            error: {
              iconTheme: {
                primary: "#ef4444",
                secondary: "#0a0a0a",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
