import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import NavBar from "./components/ui/NavBar";

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geist.variable} ${geistMono.variable} ${nunito.variable} h-full antialiased`}
    >
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
